# Generated by Django 6.0.6 on 2026-06-15 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('coins', models.IntegerField(default=100, verbose_name='Монеты')),
                ('xp', models.IntegerField(default=0, verbose_name='Опыт')),
                ('hearts', models.IntegerField(default=5, verbose_name='Жизни')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
