# Generated by Django 6.0.6 on 2026-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='temporary_password', max_length=128, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
